### ISSUE TITLE
Mexico not available as issuing country when selecting Identity card

### ISSUE THREAD

**Issue by anttilbc** [onfido/onfido-sdk-ui#1362]
### What was the expected behaviour?
Expected to find Mexico in the issuing country list when selecting Identity card as a document type.  Voter Id (INE) is listed in the supported documents

### What happened instead?
Could not find Mexico in the list

### Version info:
- Onfido SDK 6.4.0 but seems to happen with newer version as well

### Steps to reproduce:
Select Identity card as document type and in the issuing country selection Mexico is not available 

### Demo:

https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/

**Comment by anttilbc** [comment]
Hi @kushal-onfido 

Thank you for the quick reply. Sorry if I'm missing something but what should we instruct the users with Mexican Voter ID (INE) to do in this case?

**Comment by kushal-onfido** [comment]
Hi @anttilbc 
In this case, I would suggest selecting any of the available countries from the list while uploading the Mexico identity card, because the document validation will be done during the check processing in the backend. 

The alternative is if you have the Driving License document type option enabled, also the user can select that and Mexico should be available as an option in the country selection list. In both cases, the document validation is done at the backend during the check processing. 

I hope it helps!
