### ISSUE TITLE
Possible incorrect spelling of driving_license label on document step.

### ISSUE THREAD

**Issue by wolfflow** [onfido/onfido-sdk-ui#257]
Hi, seems that it should be **Driving license** instead of **Driver's license**, same as in docs: https://documentation.onfido.com/#document-types

See: 
https://github.com/onfido/onfido-sdk-ui/blob/ca12423c1b079e10f3fcf803447e41da51d690c5/src/components/DocumentSelector/index.js#L12

Would you mind changing it? Thanks in advance.

**Comment by hjheath** [comment]
Hi, thanks for raising this issue.

The `label` field is only used as copy in the UI. The `value` field is used to tell our API what document type we are uploading.  So in this case `value: 'driving_licence'` does match the API documentation and so we are sending the document type correctly.

Let me know if that makes sense. Also let me know if I have misunderstood and you are suggesting we change the copy text used in the UI.

**Comment by wolfflow** [comment]
Hi, sorry for an ambiguous title. Actually I suggested you to change the copy text, not the constant of course) So, finally it's just simple as changing Driver's license --> Driving license.
Have a good day!

**Comment by hjheath** [comment]
OK thanks for clarifying. We are trying to make our products as international as possible and we think that `Driver's license` is the most widely understood term. Therefore the SDK copy is correct and we need to update our API documentation - I will raise an internal ticket.

I would be interested in why you raised this as a concern - is the term we use important to you one way or the other? Let me know, otherwise I will close this issue.
