### ISSUE TITLE
Websocket connection on Safari - Error 400

### ISSUE THREAD

**Issue by TAiS46** [onfido/onfido-sdk-ui#323]
1. Open: http://jsfiddle.net/4xqtt6fL/176/
2. start process, choose document type, click `need to use your mobile to take  photos?`
3. step keeps loading, 400 error in console

```
{
    "code": 1,
    "message": "Session ID unknown"
}
```

**Comment by rfreitas** [comment]
Hi @TAiS46, we found the reason to this problem.
It's related to the Safari Privacy option of Prevent Cross-site tracking. By disabling this option you will see it will start to work.
We have done a temporary fix on our backend to fix this issue and we are working on a longer term solution for it.

The reason for this issue is because our load balancer is using cookies to provide stickiness, necessary for the cross device feature to work. With the "Prevent Cross-site tracking" option enabled, third party cookies are not accepted and hence the stickiness does not work. (Interestingly enough, if you visit an onfido domain then that third party cookie gets upgraded to first party and the whole thing starts to work.)
