### ISSUE TITLE
Load style.css in production mode

### ISSUE THREAD

**Issue by HoneyryderChuck** [onfido/onfido-sdk-ui#352]
We're currently shipping the onfido bundle we use in development, i.e. the one which also loads the styles during initialization. 

We're now trying to optimize this and use the `onfido.min.js` (using webpack's alias resolve). This does not work, as the styles aren't lazy-loaded anymore. We have to bind the `dist/style.css` ourselves.

This hasn't been possible, however. As soon as I set up the alias to the `min.js` version, all `style.css` imports fail. I could try to set it up with a style tag in the index.html, but I'd lose the ability to lazy-load it (this is something that we need).

I think that the documentation could be improved with some examples for production set-ups, specifically how to make the `/dist` assets work well in a react/webpack scenario, with or without lazy loading (just setting `<link rel='stylesheet' href='dist/style.css'>` won't cut it for most, I think).

**Comment by rfreitas** [comment]
Hi @HoneyryderChuck ,

Are you trying to import the sdk through npm? Is that what makes it impossible for you to lazy load the styles? If so, that is correct and it is a point that needs improvement.

As a workaround, you can import the js file from `dist` folder and since the style is in its own separate file, you will be able to lazy load it. However, you cannot use require, because that will not use the `dist` file, it will use a different bundle, the one with the style already embedded.

In order to consume our sdk with webpack, the recommended approach is to version the js file and treat it like a js file import rather than an npm import.

With regards to the documentation lacking, you make a good point.

**Comment by stefaniacardenas** [comment]
Hi, I hope the previous reply answered your questions. I will now close this issue for inactivity. Please feel free to reopen if the problem still exists.
