### ISSUE TITLE
Users can no longer upload file for face on Desktop

### ISSUE THREAD

**Issue by Aralun** [onfido/onfido-sdk-ui#397]
On Desktop 2.5.0 users are not able to upload a file if they deny using the webcam at the face step.

This is the init code:
```javascript
const onfido = Onfido.init({
  token: '...',
  containerId: '...',
  steps: [
    {
      type: 'welcome',
      options: {
        title: 'Onfido check',
        descriptions: [
          'This is',
          'the description'
        ],
        nextButton: 'Next'
      }
    },
    'document',
    'face'
  ],
  onComplete: () => alert('complete')
})
```

Instead they are only presented with a "Refresh" button.

**Comment by seewah** [comment]
Hi

This is actually an intentional change. The reason is that, in the past, file upload tends to result in unsuitable photos being uploaded by users, which our face check inevitably fails. Examples include social network profile pictures, etc. The webcam based experience is designed to enforce "live" capture of the user's face, thus ensuring a higher pass rate for our customers.

Thanks

See Wah

**Comment by Aralun** [comment]
I agree, we do have a lot of wasted checks in regard to poor pictures being uploaded.

Shouldn't this have resulted in a new major though?
