### ISSUE TITLE
Blank page when continuing on Android browser 

### ISSUE THREAD

**Issue by andrewlock** [onfido/onfido-sdk-ui#613]
Hi, 

I'm trying to integrate the Onfido UI, but users are seeing a blank screen when continuing on Android. I see that you support Chrome, but it's a poor experience for users if they don't already have this installed, or don't have it set as their default browser. Is it possible to at least display an "unsupported browser message" in this case?

![image](https://user-images.githubusercontent.com/18755388/55557941-e7056980-56e2-11e9-9d4e-1e0344b70ab8.png)

Thanks

**Comment by stefaniacardenas** [comment]
Hi,
Is this happening on the android stock browser? Do you know on which device and browser version at all? We support latest versions of Chrome, Samsung Internet, FF and some android stock browsers. It would be great to have more details to be able to reproduce it on our side

**Comment by andrewlock** [comment]
Hi, yes it's on the stock android browser. The phone is a xiaomi redmi 5 plus - android  8.1.0. 

Let me know if  theres anything else I can do to help. Thanks!

**Comment by andrewlock** [comment]
Hi, just wondered if you have any updates on this? Thanks

**Comment by andrewlock** [comment]
Hi, I'm afraid I don't have access to the phone, but I have confirmed this is still happening. Also, as it's the stock android browser (and not Chrome) I don't think it would be possible to use remote debugging? We're currently using version 4.0.0 of the SDK, but I don't believe that should matter?

To be clear, we're not having issues with the SDK itself. The problem is when you click "Continue on Mobile", and are sent a text message with a URL like https://id.onfido.com/AOKEH2EP. When you click that message, it opens the default browser, which is where we're seeing the problem. i.e. it's Onfido's service itself, rather than our integration...

**Comment by amoyano** [comment]
Hi i'm having this issue too, is it resolved?  whe I try with my laptop
And when I try with my iphone last version safari and chrome  said
UNSUPPORTED BROWSER, restar tthe process with the last version....

thanks

**Comment by stefaniacardenas** [comment]
The native android browser is not one of the browsers we support. Please check the list of supported browsers [here](https://github.com/onfido/onfido-sdk-ui#more-information). @amoyano the issue you are facing is probably a different one as it seems to be affecting Safari and Chrome on iPhone. Please note that on older iOS versions where `getUserMedia` is not supported by the browser, if you are using the `uploadFallback: false` option, you will always see that error. If you are on an iOS version where `getUserMedia` is supported, please upgrade to the latest version of the SDK. If the issue is still present, please open a new issue and I will look into it.
