### ISSUE TITLE
Cross over on v5.1.0 from desktop to mobile (Android and iOS) shows a blank screen

### ISSUE THREAD

**Issue by badikumar** [onfido/onfido-sdk-ui#669]
When check is initiated from Desktop Chrome or Microsoft Edge and cross over to either Android Chrome/Firefox or iOS Safari (by copying link/sending link), the screen is blank on the mobile browser.

**Comment by badikumar** [comment]
FYI - we just migrated from v3.1.0 to v5.1.0 everything else works except the cross over.

**Comment by stefaniacardenas** [comment]
Hi @badikumar, thank you for reporting the issue. It was a permission problem and it should be fixed now. Many thanks

**Comment by badikumar** [comment]
great it's fixed. permission problem on your side? Nothing needs to change on our side?

**Comment by stefaniacardenas** [comment]
Nothing to change on your side @badikumar. The problem was on our side. The application that serves the bundles for the cross device mobile browser was not able to fetch the assets due to a permission error. I have now fixed the permissions on our side and you should be able to use the latest version of the SDK also on mobile.
