### ISSUE TITLE
User prompted to upload selfie when device doesn't support camera for "video" variant.

### ISSUE THREAD

**Issue by josephan** [onfido/onfido-sdk-ui#724]
![Screen Shot 2019-07-08 at 11 00 08 AM](https://user-images.githubusercontent.com/8878596/60822706-0396bf00-a174-11e9-895e-dbb88c8adcc0.png)

During the `face` step for the `variant: "video"`, the user is prompted to upload a selfie if their device doesn't have a camera.

**Comment by kopijunkie** [comment]
Hi @josephan 

Could you provide the config you are using for your implementation and the version of the SDK you are using? Some information on the device and browser would also be great. The expected behaviour for the video variant of the face step when there is no camera detected is for the user to see the selfie camera screen or the cross device introduction screen (if the SDK is unable to load the selfie camera screen also on the browser) instead.

**Comment by josephan** [comment]
@kopijunkie Sorry not providing the info with the original post:

**Comment by kopijunkie** [comment]
@josephan Thank you for the details. I was able to reproduce the issue you reported. I will raise a ticket on our end to get this bug fixed and I will update you here when it has been released.

**Comment by kopijunkie** [comment]
@josephan FYI the fix for this issue has been released with [5.3.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.3.0) that went out today.

I will close this ticket for now but do feel free to re-open if you are still seeing the issue on the latest version.
