### ISSUE TITLE
"No access to camera" iPhone X

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#892]
A report from one of our customers detailing the bug. When this person tries to confirm the back of the license photo they receive a message "No access to a camera".

> I’m using my iPhone X. It let’s me take a picture of the front of my DL, then the back. But when I press the confirm on the back picture, it tells me it has no access to a camera. That’s not the case because I just used the camera from the same process to take pictures of the front and back.

**Comment by ramprasad-parajuli** [comment]
@ctrlaltdylan , I would require the following information to investigate and debug the issue further:

- Web SDK version.
- The browser being used (name and version).
- A link to your integration/implementation, so that we could test it and try to reproduce the error.
- Issue severity details (number of users/crashes if applicable);
- Does this happen every time for this user in particular?
- Other useful information like screenshots of what the user sees when the issue occurs. For example, the headers information in the Network Tab of the browser's developer tools, when the issue is occurring.
