### ISSUE TITLE
Error when continuing document upload on mobile

### ISSUE THREAD

**Issue by diogob** [onfido/onfido-sdk-ui#925]
### What was the expected behaviour?

The user should be able to upload documents using a mobile browser following a link generated in the web based SDK. We have validated the same environment+code using the web interface to upload documents and everything worked fine.

### What happened instead?

The mobile shows an error screen and a 401 status when posting to the documents endpoint.

### Version info:

- Onfido SDK: 5.7.0
- OS: Android 9 and 13.3.1 
- Browser: Chrome 80.0.3987.117 and Safari 
- Device: one plus 5, iPhone 8
- We are using the ruby bindings to the API to generate the JWT

Also note that we have CSP on our web server and we have followed the [instructions on the readme](https://github.com/onfido/onfido-sdk-ui#troubleshooting) to properly configure the SDK parent page.

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.
JWT creation:

```ruby
onfido = Onfido::API.new(api_key: ENV['ONFIDO_API_TOKEN'])
onfido.sdk_token.create(applicant_id: applicant_id, referrer: "https://*.ourdomain.com/*")
```

Bellow is the SDK UI initialization:

```javascript
Onfido.init({
	token: token,
	containerId: 'onfido-mount-onboarding',
	onComplete: app.ports.onComplete.send,
	steps: [ 
		{
			type: 'welcome',
			options: {
				title: 'Okay, lets verify your identity!',
				descriptions: [...],
				nextButton: "Verify Identity"
			}
		},
		'document',
		'face',
		{
			type: 'complete',
			options: {
				message: 'Documents Uploaded',
				submessage: "Thanks!"
			},
		},
	],
	smsNumberCountryCode: 'CA',
	userDetails: { smsNumber: phoneNumber },
})
```

### Steps to reproduce:

1. We create the applicant
1. We generate a JWT using a sandbox token
1. We use the JWT to initialize the SDK
1. After selcting the document type we click on the `Continue on phone` button
1. We copy the link or send it via SMS to either Android or iPhone device
1. We open the link on the mobile browser
1. The websocket updates the SDK screen to acknowledge successful connection to the device (we double checked on developer tools pannel that the messages flow both ways on the websocket)
1. We take a picture through the mobile browser
1. We review the picture and click confirm
1. The loader shows up for about a second and we see an error screen on the mobile (no change in the SDK UI)

### Demo:

The screenshot bellow shows a remote debugging session on the Android device:
![Screen Shot 2020-02-25 at 6 16 20 PM](https://user-images.githubusercontent.com/20662/75396026-8a460b00-58c1-11ea-87a7-a8773d9d30c1.png)

**Comment by ramprasad-parajuli** [comment]
Hi @diogob,

Thank you for flagging the issue.

We weres able to investigate the issue and the root cause of the issue has been found. We had an issue in Web SDK where if the client is configured in our US instance, the end-users would experience 401 Error when trying to complete the flow through cross-device.

We were able to implement a fix for it and the fix has been released on our [most recent update](https://github.com/onfido/onfido-sdk-ui/blob/master/CHANGELOG.md#571---2020-02-25) which was made public yesterday. You could find more information regarding our new releases here - https://github.com/onfido/onfido-sdk-ui/blob/master/CHANGELOG.md.

Could you please update the Web SDK to our latest version i.e. 5.7.1 and let us know if you are able to successfully complete the flow through cross-device.

**Comment by diogob** [comment]
@ramprasad-parajuli everything is looking good now, thanks for the help :D
