### ISSUE TITLE
Document types list

### ISSUE THREAD

**Issue by RoyRewire** [onfido/onfido-sdk-ui#926]
Is it possible to publish a list of all the supported document types?

**Comment by ramprasad-parajuli** [comment]
@RoyRewire Do you mean a list of document types generally on our website or specifically for Web SDK? 
Because, currently, we only support Driving License, PoA, National Identity Card and Passport in our Web SDK. We might be looking into adding some more document types in the future, but I am not sure about the exact timelines.
